// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgresrepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Benefit struct {
	ID             int32       `json:"id"`
	BenefitKey     string      `json:"benefit_key"`
	BenefitOrderID pgtype.Text `json:"benefit_order_id"`
	BenefitType    pgtype.Text `json:"benefit_type"`
}

type Billing struct {
	ID                     int32          `json:"id"`
	PartnerKey             pgtype.Text    `json:"partner_key"`
	CustomerKey            pgtype.Text    `json:"customer_key"`
	ProductKey             pgtype.Text    `json:"product_key"`
	PublisherKey           pgtype.Text    `json:"publisher_key"`
	SubscriptionKey        pgtype.Text    `json:"subscription_key"`
	MetersKey              pgtype.Text    `json:"meters_key"`
	ResourceUri            pgtype.Text    `json:"resource_uri"`
	EntitlementKey         pgtype.Text    `json:"entitlement_key"`
	BenefitKey             pgtype.Text    `json:"benefit_key"`
	Invoice                pgtype.Text    `json:"invoice"`
	UnitPrice              pgtype.Numeric `json:"unit_price"`
	Quantity               pgtype.Numeric `json:"quantity"`
	UnitType               pgtype.Text    `json:"unit_type"`
	BillingPreTaxTotal     pgtype.Numeric `json:"billing_pre_tax_total"`
	BillingCurrency        pgtype.Text    `json:"billing_currency"`
	PricingPreTaxTotal     pgtype.Numeric `json:"pricing_pre_tax_total"`
	PricingCurrency        pgtype.Text    `json:"pricing_currency"`
	EffectiveUnitPrice     pgtype.Numeric `json:"effective_unit_price"`
	PcToBcExchangeRate     pgtype.Numeric `json:"pc_to_bc_exchange_rate"`
	PcToBcExchangeRateDate pgtype.Date    `json:"pc_to_bc_exchange_rate_date"`
	ChargeStartDate        pgtype.Date    `json:"charge_start_date"`
	ChargeEndDate          pgtype.Date    `json:"charge_end_date"`
	UsageDate              pgtype.Date    `json:"usage_date"`
	ChargeType             pgtype.Text    `json:"charge_type"`
}

type Customer struct {
	ID          int32       `json:"id"`
	CustomerKey string      `json:"customer_key"`
	Name        pgtype.Text `json:"name"`
	DomainName  pgtype.Text `json:"domain_name"`
	Country     pgtype.Text `json:"country"`
	TierToMpnID pgtype.Text `json:"tier_to_mpn_id"`
}

type Entitlement struct {
	ID             int32       `json:"id"`
	EntitlementKey string      `json:"entitlement_key"`
	Description    pgtype.Text `json:"description"`
}

type Meter struct {
	ID          int32       `json:"id"`
	MetersKey   string      `json:"meters_key"`
	Type        pgtype.Text `json:"type"`
	Category    pgtype.Text `json:"category"`
	SubCategory pgtype.Text `json:"sub_category"`
	Name        pgtype.Text `json:"name"`
	Region      pgtype.Text `json:"region"`
	Unit        pgtype.Text `json:"unit"`
}

type Partner struct {
	ID         int32       `json:"id"`
	PartnerKey string      `json:"partner_key"`
	Name       pgtype.Text `json:"name"`
	MpnID      pgtype.Text `json:"mpn_id"`
}

type Product struct {
	ID         int32       `json:"id"`
	ProductKey string      `json:"product_key"`
	Name       pgtype.Text `json:"name"`
	SkuID      pgtype.Text `json:"sku_id"`
}

type Publisher struct {
	ID           int32       `json:"id"`
	PublisherKey string      `json:"publisher_key"`
	Name         pgtype.Text `json:"name"`
}

type Resource struct {
	ID              int32       `json:"id"`
	Uri             string      `json:"uri"`
	Location        pgtype.Text `json:"location"`
	ConsumedService pgtype.Text `json:"consumed_service"`
	ResourceGroup   pgtype.Text `json:"resource_group"`
	Info1           pgtype.Text `json:"info1"`
	Info2           pgtype.Text `json:"info2"`
	Tags            pgtype.Text `json:"tags"`
	AdditionalInfo  pgtype.Text `json:"additional_info"`
}

type Sku struct {
	ID             int32       `json:"id"`
	SkuKey         string      `json:"sku_key"`
	Name           pgtype.Text `json:"name"`
	AvailabilityID pgtype.Text `json:"availability_id"`
}

type Subscription struct {
	ID              int32       `json:"id"`
	SubscriptionKey string      `json:"subscription_key"`
	Description     pgtype.Text `json:"description"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
